# -*- coding: utf-8 -*-
"""
AI因子模块
提供各种AI增强的投资因子和自动策略生成功能
"""

from .factor_manager import FactorManager, BaseFactor, FactorValue, FactorDefinition, get_factor_manager
from .technical_ai_factors import PatternRecognitionFactor, VolumePatternFactor, register_technical_ai_factors
from .price_prediction_factors import PricePredictionFactor, ReturnPredictionFactor, register_prediction_factors
from .market_enhanced_factors import MarketBetaAdjustedFactor, MarketRelativeStrengthFactor
from .multi_timeframe_factors import MultiTimeframeRSIFactor, MultiTimeframeMACDFactor, create_multi_timeframe_rsi_factor, create_multi_timeframe_macd_factor
from .timeframe_weight_optimizer import TimeframeWeightOptimizer, get_timeframe_weight_optimizer, optimize_timeframe_weights, TimeframeWeightResult, TimeframeSignalPerformance
from .factor_validator import FactorValidator, validate_factor_simple
from .auto_factor_selector import AutoFactorSelector, FactorPerformance, SelectionCriteria
from .factor_weight_optimizer import FactorWeightOptimizer, OptimizationMethod, OptimizationConstraints, optimize_factor_weights
from .auto_strategy_generator import AutoStrategyGenerator, GeneratedStrategy, StrategyParameters, generate_auto_strategy
from .strategy_dynamic_adjuster import StrategyDynamicAdjuster, MarketMetrics, StrategyPerformanceMetrics, create_market_metrics, create_performance_metrics
from .auto_factor_generator import AutoFactorGenerator, GeneratedFactorInfo, AutoGeneratedFactor, create_auto_factor_generator, generate_new_factors
from .fundamental_factors import (
    ValuePEFactor, ValuePBFactor, ProfitabilityROEFactor,
    GrowthRevenueFactor, ProfitQualityFactor, FinancialHealthFactor
)
from .factor_momentum_factors import (
    FactorMomentum3dFactor, FactorMomentum5dFactor,
    FactorMomentum15dFactor, FactorMomentum20dFactor,
    register_factor_momentum_factors
)

# 注册市场增强因子
def register_market_enhanced_factors():
    """注册市场增强因子"""
    manager = get_factor_manager()
    manager.register_factor(MarketBetaAdjustedFactor())
    manager.register_factor(MarketRelativeStrengthFactor())

# 注册基本面因子
def register_fundamental_factors():
    """注册基本面因子（PE/PB/ROE/营收增长/毛利率/财务健康）"""
    try:
        manager = get_factor_manager()

        # 注册6个基本面因子
        manager.register_factor(ValuePEFactor())
        manager.register_factor(ValuePBFactor())
        manager.register_factor(ProfitabilityROEFactor())
        manager.register_factor(GrowthRevenueFactor())
        manager.register_factor(ProfitQualityFactor())
        manager.register_factor(FinancialHealthFactor())

        print(f"✓ 基本面因子已注册: value_pe, value_pb, profitability_roe, growth_revenue, profit_quality, financial_health")
    except Exception as e:
        print(f"注册基本面因子失败: {e}")
        import traceback
        traceback.print_exc()

# 注册多时间框架因子
def register_multi_timeframe_factors(config: dict = None):
    """注册多时间框架因子

    Args:
        config: 配置字典，包含multi_timeframe_factors配置
    """
    try:
        manager = get_factor_manager()

        # 如果配置中启用了多时间框架因子
        if config is None:
            from config.config_manager import get_config
            config = get_config()

        mtf_config = config.get('system_settings', {}).get('multi_timeframe_factors', {})

        if not mtf_config.get('enabled', True):
            print("多时间框架因子未启用")
            return

        # 注册RSI因子
        rsi_factor = MultiTimeframeRSIFactor(mtf_config)
        manager.register_factor(rsi_factor)

        # 注册MACD因子
        macd_factor = MultiTimeframeMACDFactor(mtf_config)
        manager.register_factor(macd_factor)

        print(f"✓ 多时间框架因子已注册: {rsi_factor.name}, {macd_factor.name}")

    except Exception as e:
        print(f"注册多时间框架因子失败: {e}")
        import traceback
        traceback.print_exc()

# 自动注册所有因子
def initialize_factors(enable_auto_generation: bool = True):
    """初始化并注册所有因子"""
    register_technical_ai_factors()
    register_prediction_factors()
    register_market_enhanced_factors()  # 注册市场增强因子
    register_multi_timeframe_factors()   # 注册多时间框架因子
    register_fundamental_factors()       # 注册基本面因子
    register_factor_momentum_factors()   # 注册因子动量因子

    # 如果启用自动因子生成
    if enable_auto_generation:
        try:
            results = generate_new_factors(template_count=2, ai_count=1)
            print(f"AI因子模块初始化完成，自动生成 {results['total_registered']} 个新因子")
        except Exception as e:
            print(f"AI因子模块初始化完成，自动因子生成失败: {e}")
    else:
        print("AI因子模块初始化完成")

# 模块级别的便捷函数
def get_all_factors(symbol: str, data: dict, categories: list = None):
    """获取所有因子值的便捷函数"""
    manager = get_factor_manager()
    return manager.calculate_all_factors(symbol, data, categories)

def get_factor_matrix(symbols: list, factor_names: list = None):
    """获取因子矩阵的便捷函数"""
    manager = get_factor_manager()
    return manager.get_factor_matrix(symbols, factor_names)

def create_auto_strategy(symbols: list, returns_data: dict, factor_data: dict, strategy_type: str = "multi_factor"):
    """创建自动策略的便捷函数"""
    return generate_auto_strategy(symbols, returns_data, factor_data, strategy_type)

def validate_factors(factor_names: list, test_symbols: list, days_back: int = 30):
    """批量验证因子的便捷函数"""
    results = {}
    for factor_name in factor_names:
        try:
            result = validate_factor_simple(factor_name, test_symbols, days_back)
            results[factor_name] = result
        except Exception as e:
            results[factor_name] = {"error": str(e)}
    return results

def get_auto_factor_summary():
    """获取自动生成因子的摘要"""
    generator = create_auto_factor_generator()
    return generator.get_generated_factors_summary()

def generate_additional_factors(template_count: int = 3, ai_count: int = 2):
    """生成额外的因子"""
    return generate_new_factors(template_count, ai_count)

__all__ = [
    # 核心组件
    'FactorManager', 'BaseFactor', 'FactorValue', 'FactorDefinition',
    'PatternRecognitionFactor', 'VolumePatternFactor',
    'PricePredictionFactor', 'ReturnPredictionFactor',
    'MarketBetaAdjustedFactor', 'MarketRelativeStrengthFactor',
    'MultiTimeframeRSIFactor', 'MultiTimeframeMACDFactor',
    'ValuePEFactor', 'ValuePBFactor', 'ProfitabilityROEFactor',
    'GrowthRevenueFactor', 'ProfitQualityFactor', 'FinancialHealthFactor',
    'FactorMomentum3dFactor', 'FactorMomentum5dFactor',
    'FactorMomentum15dFactor', 'FactorMomentum20dFactor',

    # 自动化组件
    'AutoFactorSelector', 'FactorPerformance', 'SelectionCriteria',
    'FactorWeightOptimizer', 'OptimizationMethod', 'OptimizationConstraints',
    'TimeframeWeightOptimizer', 'TimeframeWeightResult', 'TimeframeSignalPerformance',
    'AutoStrategyGenerator', 'GeneratedStrategy', 'StrategyParameters',
    'StrategyDynamicAdjuster', 'MarketMetrics', 'StrategyPerformanceMetrics',
    'FactorValidator',

    # 自动因子生成组件
    'AutoFactorGenerator', 'GeneratedFactorInfo', 'AutoGeneratedFactor',

    # 便捷函数
    'get_factor_manager', 'initialize_factors',
    'get_all_factors', 'get_factor_matrix', 'create_auto_strategy',
    'validate_factors', 'validate_factor_simple', 'optimize_factor_weights',
    'generate_auto_strategy', 'create_market_metrics', 'create_performance_metrics',
    'create_auto_factor_generator', 'generate_new_factors', 'get_auto_factor_summary', 'generate_additional_factors',
    'register_prediction_factors', 'register_multi_timeframe_factors', 'register_fundamental_factors',
    'register_factor_momentum_factors',
    'create_multi_timeframe_rsi_factor', 'create_multi_timeframe_macd_factor',
    'get_timeframe_weight_optimizer', 'optimize_timeframe_weights'
]