# -*- coding: utf-8 -*-
"""
自动因子生成器
基于模板和AI技术自动生成新的投资因子
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Optional, Tuple, Any, Callable
import logging
from datetime import datetime
from dataclasses import dataclass
from enum import Enum
import json
import random
import string
from scipy import stats
from scipy.signal import find_peaks
import warnings
warnings.filterwarnings('ignore')

from .factor_manager import BaseFactor, FactorValue, get_factor_manager

logger = logging.getLogger(__name__)

class FactorType(Enum):
    """因子类型"""
    TECHNICAL = "technical"
    FUNDAMENTAL = "fundamental"
    SENTIMENT = "sentiment"
    VOLUME = "volume"
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    VOLATILITY = "volatility"
    CROSS_SECTIONAL = "cross_sectional"

class GenerationMethod(Enum):
    """生成方法"""
    TEMPLATE_BASED = "template_based"
    AI_ENHANCED = "ai_enhanced"
    HYBRID = "hybrid"

@dataclass
class FactorTemplate:
    """因子模板"""
    template_id: str
    name_pattern: str
    description_pattern: str
    factor_type: FactorType
    required_data: List[str]
    calculation_template: str
    parameter_ranges: Dict[str, Tuple[float, float]]
    complexity_level: int  # 1-5, 复杂度等级

@dataclass
class GeneratedFactorInfo:
    """生成因子信息"""
    factor_id: str
    factor_name: str
    factor_type: FactorType
    description: str
    generation_method: GenerationMethod
    template_used: Optional[str]
    parameters: Dict[str, Any]
    expected_effectiveness: float
    generation_time: datetime
    source_code: str

class AutoGeneratedFactor(BaseFactor):
    """自动生成的因子"""
    
    def __init__(self, info: GeneratedFactorInfo, calculation_func: Callable):
        super().__init__(
            name=info.factor_name,
            category=info.factor_type.value,
            description=info.description
        )
        self.generation_info = info
        self.calculation_func = calculation_func
        self.dependencies = ["price", "volume"]  # 默认依赖
        
    def calculate(self, data: Dict[str, pd.DataFrame], symbol: str, **kwargs) -> FactorValue:
        """计算因子值"""
        try:
            value = self.calculation_func(data, symbol, **self.generation_info.parameters)
            
            return FactorValue(
                symbol=symbol,
                factor_name=self.name,
                value=value,
                timestamp=datetime.now(),
                confidence=self.generation_info.expected_effectiveness,
                metadata={
                    'generation_method': self.generation_info.generation_method.value,
                    'template_used': self.generation_info.template_used,
                    'generation_time': self.generation_info.generation_time.isoformat()
                }
            )
            
        except Exception as e:
            logger.error(f"自动生成因子 {self.name} 计算失败: {e}")
            return FactorValue(symbol, self.name, 0.0, datetime.now(), 0.0)

class AutoFactorGenerator:
    """自动因子生成器"""
    
    def __init__(self):
        self.factor_manager = get_factor_manager()
        self.templates = self._create_default_templates()
        self.generated_factors = []
        self.generation_history = []
        
    def _create_default_templates(self) -> List[FactorTemplate]:
        """创建默认因子模板"""
        templates = []
        
        # 动量因子模板
        templates.append(FactorTemplate(
            template_id="momentum_simple",
            name_pattern="momentum_{period}d",
            description_pattern="过去{period}天的价格动量因子",
            factor_type=FactorType.MOMENTUM,
            required_data=["price"],
            calculation_template="""
def calculate_momentum(data, symbol, period=20):
    closes = data['price']['Close'].tail(period + 1)
    if len(closes) < 2:
        return 0.0
    return (closes.iloc[-1] - closes.iloc[0]) / closes.iloc[0]
""",
            parameter_ranges={"period": (5, 60)},
            complexity_level=1
        ))
        
        # 波动率因子模板
        templates.append(FactorTemplate(
            template_id="volatility_rolling",
            name_pattern="volatility_{period}d",
            description_pattern="滚动{period}天价格波动率因子",
            factor_type=FactorType.VOLATILITY,
            required_data=["price"],
            calculation_template="""
def calculate_volatility(data, symbol, period=20):
    closes = data['price']['Close'].tail(period)
    if len(closes) < 2:
        return 0.0
    returns = closes.pct_change().dropna()
    return returns.std()
""",
            parameter_ranges={"period": (5, 90)},
            complexity_level=1
        ))
        
        # 量价关系因子模板
        templates.append(FactorTemplate(
            template_id="volume_price_correlation",
            name_pattern="vp_corr_{period}d",
            description_pattern="过去{period}天量价相关性因子",
            factor_type=FactorType.VOLUME,
            required_data=["price", "volume"],
            calculation_template="""
def calculate_vp_correlation(data, symbol, period=20):
    df_price = data['price'].tail(period)
    df_volume = data['volume'].tail(period)
    if len(df_price) < 5 or len(df_volume) < 5:
        return 0.0
    
    price_changes = df_price['Close'].pct_change().dropna()
    volume_changes = df_volume['Volume'].pct_change().dropna()
    
    min_len = min(len(price_changes), len(volume_changes))
    if min_len < 3:
        return 0.0
        
    price_changes = price_changes.tail(min_len)
    volume_changes = volume_changes.tail(min_len)
    
    correlation = np.corrcoef(price_changes, volume_changes)[0, 1]
    return 0.0 if np.isnan(correlation) else correlation
""",
            parameter_ranges={"period": (10, 60)},
            complexity_level=2
        ))
        
        # 反转因子模板
        templates.append(FactorTemplate(
            template_id="mean_reversion",
            name_pattern="reversion_{period}d_{threshold}",
            description_pattern="均值回归因子，基于{period}天均线偏离度{threshold}",
            factor_type=FactorType.MEAN_REVERSION,
            required_data=["price"],
            calculation_template="""
def calculate_mean_reversion(data, symbol, period=20, threshold=0.05):
    closes = data['price']['Close'].tail(period + 1)
    if len(closes) < period:
        return 0.0
    
    current_price = closes.iloc[-1]
    moving_avg = closes.iloc[:-1].mean()
    
    if moving_avg == 0:
        return 0.0
        
    deviation = (current_price - moving_avg) / moving_avg
    
    # 当偏离超过阈值时，预期回归
    if abs(deviation) > threshold:
        return -deviation  # 反向信号
    else:
        return 0.0
""",
            parameter_ranges={"period": (10, 50), "threshold": (0.02, 0.15)},
            complexity_level=2
        ))
        
        # 技术形态因子模板
        templates.append(FactorTemplate(
            template_id="technical_pattern",
            name_pattern="pattern_{lookback}d_{sensitivity}",
            description_pattern="技术形态识别因子，回看{lookback}天，敏感度{sensitivity}",
            factor_type=FactorType.TECHNICAL,
            required_data=["price"],
            calculation_template="""
def calculate_technical_pattern(data, symbol, lookback=30, sensitivity=0.02):
    df = data['price'].tail(lookback)
    if len(df) < 10:
        return 0.0
    
    highs = df['High'].values
    lows = df['Low'].values
    closes = df['Close'].values
    
    # 寻找局部极值
    high_peaks, _ = find_peaks(highs, distance=3)
    low_peaks, _ = find_peaks(-lows, distance=3)
    
    score = 0.0
    current_price = closes[-1]
    
    # 支撑阻力分析
    if len(high_peaks) > 0:
        resistance_levels = highs[high_peaks]
        nearest_resistance = resistance_levels[np.argmin(np.abs(resistance_levels - current_price))]
        if nearest_resistance > current_price:
            resistance_distance = (nearest_resistance - current_price) / current_price
            if resistance_distance < sensitivity:
                score -= 0.5  # 接近阻力位，负面信号
    
    if len(low_peaks) > 0:
        support_levels = lows[low_peaks]
        nearest_support = support_levels[np.argmin(np.abs(support_levels - current_price))]
        if nearest_support < current_price:
            support_distance = (current_price - nearest_support) / current_price
            if support_distance < sensitivity:
                score += 0.5  # 接近支撑位，正面信号
    
    return score
""",
            parameter_ranges={"lookback": (15, 60), "sensitivity": (0.01, 0.10)},
            complexity_level=3
        ))
        
        return templates
    
    def generate_factors_from_templates(self, count: int = 3, 
                                      factor_types: List[FactorType] = None) -> List[GeneratedFactorInfo]:
        """基于模板生成因子"""
        logger.info(f"开始基于模板生成 {count} 个因子...")
        
        if factor_types is None:
            factor_types = [FactorType.MOMENTUM, FactorType.VOLUME, FactorType.VOLATILITY, 
                          FactorType.MEAN_REVERSION, FactorType.TECHNICAL]
        
        generated_factors = []
        
        for i in range(count):
            try:
                # 随机选择因子类型和模板
                target_type = random.choice(factor_types)
                suitable_templates = [t for t in self.templates if t.factor_type == target_type]
                
                if not suitable_templates:
                    continue
                
                template = random.choice(suitable_templates)
                
                # 生成随机参数
                parameters = {}
                for param_name, (min_val, max_val) in template.parameter_ranges.items():
                    if isinstance(min_val, int) and isinstance(max_val, int):
                        parameters[param_name] = random.randint(min_val, max_val)
                    else:
                        parameters[param_name] = round(random.uniform(min_val, max_val), 3)
                
                # 生成因子名称和描述
                factor_name = template.name_pattern.format(**parameters)
                description = template.description_pattern.format(**parameters)
                
                # 确保因子名称唯一
                factor_id = f"auto_{factor_name}_{self._generate_unique_id()}"
                
                # 计算预期有效性
                expected_effectiveness = self._estimate_factor_effectiveness(template, parameters)
                
                # 创建因子信息
                factor_info = GeneratedFactorInfo(
                    factor_id=factor_id,
                    factor_name=factor_name,
                    factor_type=target_type,
                    description=description,
                    generation_method=GenerationMethod.TEMPLATE_BASED,
                    template_used=template.template_id,
                    parameters=parameters,
                    expected_effectiveness=expected_effectiveness,
                    generation_time=datetime.now(),
                    source_code=template.calculation_template
                )
                
                generated_factors.append(factor_info)
                logger.info(f"生成因子: {factor_name} (预期效果: {expected_effectiveness:.3f})")
                
            except Exception as e:
                logger.error(f"生成第{i+1}个因子时出错: {e}")
        
        logger.info(f"基于模板成功生成 {len(generated_factors)} 个因子")
        return generated_factors
    
    def generate_ai_enhanced_factors(self, count: int = 2) -> List[GeneratedFactorInfo]:
        """生成AI增强因子"""
        logger.info(f"开始生成 {count} 个AI增强因子...")
        
        generated_factors = []
        
        for i in range(count):
            try:
                # AI增强策略：组合多个基础指标
                factor_name = f"ai_composite_{self._generate_unique_id()}"
                
                # 随机选择组合策略
                strategies = ["momentum_volatility", "volume_pattern", "multi_timeframe", "adaptive_threshold"]
                strategy = random.choice(strategies)
                
                if strategy == "momentum_volatility":
                    factor_info = self._create_momentum_volatility_factor(factor_name)
                elif strategy == "volume_pattern":
                    factor_info = self._create_volume_pattern_factor(factor_name)
                elif strategy == "multi_timeframe":
                    factor_info = self._create_multi_timeframe_factor(factor_name)
                else:  # adaptive_threshold
                    factor_info = self._create_adaptive_threshold_factor(factor_name)
                
                generated_factors.append(factor_info)
                logger.info(f"生成AI增强因子: {factor_name} (策略: {strategy})")
                
            except Exception as e:
                logger.error(f"生成第{i+1}个AI增强因子时出错: {e}")
        
        logger.info(f"成功生成 {len(generated_factors)} 个AI增强因子")
        return generated_factors
    
    def _create_momentum_volatility_factor(self, factor_name: str) -> GeneratedFactorInfo:
        """创建动量-波动率组合因子"""
        
        def calculate_momentum_volatility(data, symbol, short_period=5, long_period=20, vol_period=10):
            try:
                closes = data['price']['Close'].tail(long_period + 5)
                if len(closes) < long_period:
                    return 0.0
                
                # 短期动量
                short_momentum = (closes.iloc[-1] - closes.iloc[-short_period]) / closes.iloc[-short_period]
                
                # 长期动量
                long_momentum = (closes.iloc[-1] - closes.iloc[-long_period]) / closes.iloc[-long_period]
                
                # 波动率调整
                recent_returns = closes.pct_change().tail(vol_period).dropna()
                volatility = recent_returns.std() if len(recent_returns) > 1 else 0.1
                
                # AI增强：动态权重分配
                if volatility > 0.03:  # 高波动环境
                    momentum_score = short_momentum * 0.7 + long_momentum * 0.3
                else:  # 低波动环境
                    momentum_score = short_momentum * 0.4 + long_momentum * 0.6
                
                # 波动率调整
                adjusted_score = momentum_score / (1 + volatility * 10)
                
                return np.tanh(adjusted_score * 5)  # 标准化到[-1, 1]
                
            except Exception:
                return 0.0
        
        # 动态生成源代码字符串
        source_code = """
def calculate_momentum_volatility(data, symbol, short_period=5, long_period=20, vol_period=10):
    closes = data['price']['Close'].tail(long_period + 5)
    if len(closes) < long_period:
        return 0.0
    
    short_momentum = (closes.iloc[-1] - closes.iloc[-short_period]) / closes.iloc[-short_period]
    long_momentum = (closes.iloc[-1] - closes.iloc[-long_period]) / closes.iloc[-long_period]
    
    recent_returns = closes.pct_change().tail(vol_period).dropna()
    volatility = recent_returns.std() if len(recent_returns) > 1 else 0.1
    
    if volatility > 0.03:
        momentum_score = short_momentum * 0.7 + long_momentum * 0.3
    else:
        momentum_score = short_momentum * 0.4 + long_momentum * 0.6
    
    adjusted_score = momentum_score / (1 + volatility * 10)
    return np.tanh(adjusted_score * 5)
"""
        
        return GeneratedFactorInfo(
            factor_id=f"ai_{factor_name}",
            factor_name=factor_name,
            factor_type=FactorType.MOMENTUM,
            description="AI增强的动量-波动率自适应因子，根据市场波动率动态调整动量权重",
            generation_method=GenerationMethod.AI_ENHANCED,
            template_used=None,
            parameters={"short_period": 5, "long_period": 20, "vol_period": 10},
            expected_effectiveness=0.72,
            generation_time=datetime.now(),
            source_code=source_code
        )
    
    def _create_volume_pattern_factor(self, factor_name: str) -> GeneratedFactorInfo:
        """创建量价模式识别因子"""
        
        source_code = """
def calculate_volume_pattern(data, symbol, pattern_period=15, volume_threshold=1.5):
    price_df = data['price'].tail(pattern_period)
    volume_df = data['volume'].tail(pattern_period)
    
    if len(price_df) < 10 or len(volume_df) < 10:
        return 0.0
    
    closes = price_df['Close'].values
    volumes = volume_df['Volume'].values
    
    # 检测量价背离
    price_changes = np.diff(closes) / closes[:-1]
    volume_changes = np.diff(volumes) / volumes[:-1]
    
    # 寻找异常成交量
    volume_mean = np.mean(volumes)
    volume_std = np.std(volumes)
    abnormal_volume_mask = volumes > (volume_mean + volume_threshold * volume_std)
    
    pattern_score = 0.0
    
    if np.any(abnormal_volume_mask):
        # 分析异常成交量期间的价格行为
        abnormal_indices = np.where(abnormal_volume_mask)[0]
        for idx in abnormal_indices[-3:]:  # 最近3次异常
            if idx > 0:
                price_impact = price_changes[idx-1]
                volume_impact = volume_changes[idx-1]
                
                # 量价协同性分析
                if price_impact * volume_impact > 0:
                    pattern_score += 0.3  # 协同为正信号
                else:
                    pattern_score -= 0.2  # 背离为负信号
    
    return np.tanh(pattern_score)
"""
        
        return GeneratedFactorInfo(
            factor_id=f"ai_{factor_name}",
            factor_name=factor_name,
            factor_type=FactorType.VOLUME,
            description="AI量价模式识别因子，检测异常成交量与价格变动的协同性",
            generation_method=GenerationMethod.AI_ENHANCED,
            template_used=None,
            parameters={"pattern_period": 15, "volume_threshold": 1.5},
            expected_effectiveness=0.68,
            generation_time=datetime.now(),
            source_code=source_code
        )
    
    def _create_multi_timeframe_factor(self, factor_name: str) -> GeneratedFactorInfo:
        """创建多时间框架因子"""
        
        source_code = """
def calculate_multi_timeframe(data, symbol, short_tf=5, medium_tf=15, long_tf=30):
    closes = data['price']['Close'].tail(long_tf + 5)
    if len(closes) < long_tf:
        return 0.0
    
    # 多时间框架趋势分析
    short_trend = closes.tail(short_tf).diff().mean()
    medium_trend = closes.tail(medium_tf).diff().mean()
    long_trend = closes.tail(long_tf).diff().mean()
    
    # 趋势一致性评分
    trends = [short_trend, medium_trend, long_trend]
    trend_signs = [1 if t > 0 else -1 if t < 0 else 0 for t in trends]
    
    consistency = abs(sum(trend_signs)) / len(trends)  # 一致性度量
    
    # 加权综合趋势
    weighted_trend = (short_trend * 0.5 + medium_trend * 0.3 + long_trend * 0.2)
    
    # AI增强：根据一致性调整信号强度
    final_score = weighted_trend * consistency
    
    return np.tanh(final_score * 100)
"""
        
        return GeneratedFactorInfo(
            factor_id=f"ai_{factor_name}",
            factor_name=factor_name,
            factor_type=FactorType.TECHNICAL,
            description="AI多时间框架趋势因子，综合短中长期趋势一致性分析",
            generation_method=GenerationMethod.AI_ENHANCED,
            template_used=None,
            parameters={"short_tf": 5, "medium_tf": 15, "long_tf": 30},
            expected_effectiveness=0.75,
            generation_time=datetime.now(),
            source_code=source_code
        )
    
    def _create_adaptive_threshold_factor(self, factor_name: str) -> GeneratedFactorInfo:
        """创建自适应阈值因子"""
        
        source_code = """
def calculate_adaptive_threshold(data, symbol, base_period=20, adaptation_factor=0.1):
    closes = data['price']['Close'].tail(base_period * 2)
    if len(closes) < base_period:
        return 0.0
    
    # 计算动态阈值
    recent_volatility = closes.tail(base_period).pct_change().std()
    base_threshold = 0.02  # 基础阈值2%
    
    # AI自适应：根据波动率调整阈值
    adaptive_threshold = base_threshold * (1 + recent_volatility * 10)
    
    # 当前价格相对于移动平均的偏离
    moving_avg = closes.tail(base_period).mean()
    current_price = closes.iloc[-1]
    
    deviation = (current_price - moving_avg) / moving_avg
    
    # 自适应信号生成
    if abs(deviation) > adaptive_threshold:
        # 超过自适应阈值，生成反转信号
        signal_strength = min(1.0, abs(deviation) / adaptive_threshold - 1)
        return -np.sign(deviation) * signal_strength * adaptation_factor
    else:
        # 未超过阈值，趋势延续信号
        return np.sign(deviation) * adaptation_factor * 0.5
"""
        
        return GeneratedFactorInfo(
            factor_id=f"ai_{factor_name}",
            factor_name=factor_name,
            factor_type=FactorType.MEAN_REVERSION,
            description="AI自适应阈值因子，根据市场波动率动态调整反转信号阈值",
            generation_method=GenerationMethod.AI_ENHANCED,
            template_used=None,
            parameters={"base_period": 20, "adaptation_factor": 0.1},
            expected_effectiveness=0.70,
            generation_time=datetime.now(),
            source_code=source_code
        )
    
    def _estimate_factor_effectiveness(self, template: FactorTemplate, parameters: Dict) -> float:
        """估算因子有效性"""
        base_effectiveness = {
            1: 0.45,  # 简单因子
            2: 0.55,  # 中等复杂因子  
            3: 0.65,  # 复杂因子
            4: 0.70,  # 很复杂因子
            5: 0.75   # 最复杂因子
        }.get(template.complexity_level, 0.50)
        
        # 根据参数调整
        param_adjustment = 0.0
        for param_name, value in parameters.items():
            if param_name.endswith('period'):
                # 周期参数：中等周期通常更有效
                if 10 <= value <= 30:
                    param_adjustment += 0.05
                elif value < 5 or value > 60:
                    param_adjustment -= 0.05
        
        # 添加随机性
        random_factor = random.uniform(-0.1, 0.1)
        
        final_effectiveness = base_effectiveness + param_adjustment + random_factor
        return max(0.3, min(0.9, final_effectiveness))  # 限制在[0.3, 0.9]区间
    
    def _generate_unique_id(self) -> str:
        """生成唯一ID"""
        timestamp = datetime.now().strftime("%m%d%H%M")
        random_part = ''.join(random.choices(string.ascii_lowercase + string.digits, k=4))
        return f"{timestamp}{random_part}"
    
    def register_generated_factors(self, factor_infos: List[GeneratedFactorInfo]) -> int:
        """注册生成的因子到因子管理器"""
        registered_count = 0
        
        for factor_info in factor_infos:
            try:
                # 创建计算函数
                calculation_func = self._create_calculation_function(factor_info)
                
                # 创建自动生成因子实例
                auto_factor = AutoGeneratedFactor(factor_info, calculation_func)
                
                # 注册到因子管理器
                self.factor_manager.register_factor(auto_factor)
                self.generated_factors.append(auto_factor)
                
                registered_count += 1
                logger.info(f"成功注册因子: {factor_info.factor_name}")
                
            except Exception as e:
                logger.error(f"注册因子 {factor_info.factor_name} 失败: {e}")
        
        logger.info(f"成功注册 {registered_count}/{len(factor_infos)} 个自动生成因子")
        return registered_count
    
    def _create_calculation_function(self, factor_info: GeneratedFactorInfo) -> Callable:
        """根据因子信息创建计算函数"""
        
        # 根据生成方法选择不同的函数创建策略
        if factor_info.generation_method == GenerationMethod.TEMPLATE_BASED:
            return self._create_template_based_function(factor_info)
        elif factor_info.generation_method == GenerationMethod.AI_ENHANCED:
            return self._create_ai_enhanced_function(factor_info)
        else:
            return self._create_default_function(factor_info)
    
    def _create_template_based_function(self, factor_info: GeneratedFactorInfo) -> Callable:
        """为模板生成的因子创建计算函数"""
        
        # 根据模板ID选择对应的计算逻辑
        template_id = factor_info.template_used
        params = factor_info.parameters
        
        if template_id == "momentum_simple":
            def calc_func(data, symbol, **kwargs):
                period = params.get('period', 20)
                closes = data['price']['Close'].tail(period + 1)
                if len(closes) < 2:
                    return 0.0
                return (closes.iloc[-1] - closes.iloc[0]) / closes.iloc[0]
            return calc_func
            
        elif template_id == "volatility_rolling":
            def calc_func(data, symbol, **kwargs):
                period = params.get('period', 20)
                closes = data['price']['Close'].tail(period)
                if len(closes) < 2:
                    return 0.0
                returns = closes.pct_change().dropna()
                return returns.std()
            return calc_func
            
        elif template_id == "volume_price_correlation":
            def calc_func(data, symbol, **kwargs):
                period = params.get('period', 20)
                df_price = data['price'].tail(period)
                df_volume = data['volume'].tail(period)
                if len(df_price) < 5 or len(df_volume) < 5:
                    return 0.0
                
                price_changes = df_price['Close'].pct_change().dropna()
                volume_changes = df_volume['Volume'].pct_change().dropna()
                
                min_len = min(len(price_changes), len(volume_changes))
                if min_len < 3:
                    return 0.0
                    
                price_changes = price_changes.tail(min_len)
                volume_changes = volume_changes.tail(min_len)
                
                correlation = np.corrcoef(price_changes, volume_changes)[0, 1]
                return 0.0 if np.isnan(correlation) else correlation
            return calc_func
            
        elif template_id == "mean_reversion":
            def calc_func(data, symbol, **kwargs):
                period = params.get('period', 20)
                threshold = params.get('threshold', 0.05)
                closes = data['price']['Close'].tail(period + 1)
                if len(closes) < period:
                    return 0.0
                
                current_price = closes.iloc[-1]
                moving_avg = closes.iloc[:-1].mean()
                
                if moving_avg == 0:
                    return 0.0
                    
                deviation = (current_price - moving_avg) / moving_avg
                
                if abs(deviation) > threshold:
                    return -deviation
                else:
                    return 0.0
            return calc_func
            
        elif template_id == "technical_pattern":
            def calc_func(data, symbol, **kwargs):
                lookback = params.get('lookback', 30)
                sensitivity = params.get('sensitivity', 0.02)
                
                df = data['price'].tail(lookback)
                if len(df) < 10:
                    return 0.0
                
                highs = df['High'].values
                lows = df['Low'].values
                closes = df['Close'].values
                
                high_peaks, _ = find_peaks(highs, distance=3)
                low_peaks, _ = find_peaks(-lows, distance=3)
                
                score = 0.0
                current_price = closes[-1]
                
                if len(high_peaks) > 0:
                    resistance_levels = highs[high_peaks]
                    nearest_resistance = resistance_levels[np.argmin(np.abs(resistance_levels - current_price))]
                    if nearest_resistance > current_price:
                        resistance_distance = (nearest_resistance - current_price) / current_price
                        if resistance_distance < sensitivity:
                            score -= 0.5
                
                if len(low_peaks) > 0:
                    support_levels = lows[low_peaks]
                    nearest_support = support_levels[np.argmin(np.abs(support_levels - current_price))]
                    if nearest_support < current_price:
                        support_distance = (current_price - nearest_support) / current_price
                        if support_distance < sensitivity:
                            score += 0.5
                
                return score
            return calc_func
        
        # 默认函数
        return self._create_default_function(factor_info)
    
    def _create_ai_enhanced_function(self, factor_info: GeneratedFactorInfo) -> Callable:
        """为AI增强因子创建计算函数"""
        factor_name = factor_info.factor_name
        
        if "momentum_volatility" in factor_name:
            def calc_func(data, symbol, **kwargs):
                try:
                    closes = data['price']['Close'].tail(25)
                    if len(closes) < 20:
                        return 0.0
                    
                    short_momentum = (closes.iloc[-1] - closes.iloc[-5]) / closes.iloc[-5]
                    long_momentum = (closes.iloc[-1] - closes.iloc[-20]) / closes.iloc[-20]
                    
                    recent_returns = closes.pct_change().tail(10).dropna()
                    volatility = recent_returns.std() if len(recent_returns) > 1 else 0.1
                    
                    if volatility > 0.03:
                        momentum_score = short_momentum * 0.7 + long_momentum * 0.3
                    else:
                        momentum_score = short_momentum * 0.4 + long_momentum * 0.6
                    
                    adjusted_score = momentum_score / (1 + volatility * 10)
                    return np.tanh(adjusted_score * 5)
                except Exception:
                    return 0.0
            return calc_func
            
        elif "volume_pattern" in factor_name:
            def calc_func(data, symbol, **kwargs):
                try:
                    price_df = data['price'].tail(15)
                    volume_df = data['volume'].tail(15)
                    
                    if len(price_df) < 10 or len(volume_df) < 10:
                        return 0.0
                    
                    closes = price_df['Close'].values
                    volumes = volume_df['Volume'].values
                    
                    price_changes = np.diff(closes) / closes[:-1]
                    volume_changes = np.diff(volumes) / volumes[:-1]
                    
                    volume_mean = np.mean(volumes)
                    volume_std = np.std(volumes)
                    abnormal_volume_mask = volumes > (volume_mean + 1.5 * volume_std)
                    
                    pattern_score = 0.0
                    
                    if np.any(abnormal_volume_mask):
                        abnormal_indices = np.where(abnormal_volume_mask)[0]
                        for idx in abnormal_indices[-3:]:
                            if idx > 0:
                                price_impact = price_changes[idx-1]
                                volume_impact = volume_changes[idx-1]
                                
                                if price_impact * volume_impact > 0:
                                    pattern_score += 0.3
                                else:
                                    pattern_score -= 0.2
                    
                    return np.tanh(pattern_score)
                except Exception:
                    return 0.0
            return calc_func
        
        # 默认返回
        return self._create_default_function(factor_info)
    
    def _create_default_function(self, factor_info: GeneratedFactorInfo) -> Callable:
        """创建默认计算函数"""
        def default_calc_func(data, symbol, **kwargs):
            try:
                closes = data['price']['Close'].tail(20)
                if len(closes) < 2:
                    return 0.0
                return (closes.iloc[-1] - closes.iloc[0]) / closes.iloc[0]
            except Exception:
                return 0.0
        
        return default_calc_func
    
    def generate_and_register_factors(self, template_count: int = 3, ai_count: int = 2) -> Dict[str, int]:
        """生成并注册新因子到系统"""
        logger.info(f"开始自动生成因子：模板因子 {template_count} 个，AI因子 {ai_count} 个")
        
        results = {
            "template_generated": 0,
            "template_registered": 0,
            "ai_generated": 0,
            "ai_registered": 0,
            "total_registered": 0
        }
        
        try:
            # 生成模板因子
            if template_count > 0:
                template_factors = self.generate_factors_from_templates(template_count)
                results["template_generated"] = len(template_factors)
                results["template_registered"] = self.register_generated_factors(template_factors)
            
            # 生成AI增强因子
            if ai_count > 0:
                ai_factors = self.generate_ai_enhanced_factors(ai_count)
                results["ai_generated"] = len(ai_factors)
                results["ai_registered"] = self.register_generated_factors(ai_factors)
            
            results["total_registered"] = results["template_registered"] + results["ai_registered"]
            
            logger.info(f"因子生成完成: 总共注册 {results['total_registered']} 个新因子")
            
        except Exception as e:
            logger.error(f"自动因子生成过程出错: {e}")
        
        return results
    
    def get_generated_factors_summary(self) -> Dict[str, Any]:
        """获取已生成因子的摘要"""
        if not self.generated_factors:
            return {"message": "尚未生成任何因子"}
        
        summary = {
            "total_factors": len(self.generated_factors),
            "factors_by_type": {},
            "factors_by_method": {},
            "average_effectiveness": 0.0,
            "factors_list": []
        }
        
        total_effectiveness = 0.0
        
        for factor in self.generated_factors:
            info = factor.generation_info
            
            # 按类型统计
            factor_type = info.factor_type.value
            summary["factors_by_type"][factor_type] = summary["factors_by_type"].get(factor_type, 0) + 1
            
            # 按方法统计
            method = info.generation_method.value
            summary["factors_by_method"][method] = summary["factors_by_method"].get(method, 0) + 1
            
            # 累计效果
            total_effectiveness += info.expected_effectiveness
            
            # 因子列表
            summary["factors_list"].append({
                "name": info.factor_name,
                "type": factor_type,
                "method": method,
                "effectiveness": info.expected_effectiveness,
                "description": info.description[:100] + "..." if len(info.description) > 100 else info.description
            })
        
        summary["average_effectiveness"] = total_effectiveness / len(self.generated_factors)
        
        return summary


# 便捷函数
def create_auto_factor_generator() -> AutoFactorGenerator:
    """创建自动因子生成器实例"""
    return AutoFactorGenerator()

def generate_new_factors(template_count: int = 3, ai_count: int = 2) -> Dict[str, int]:
    """便捷的新因子生成函数"""
    generator = AutoFactorGenerator()
    return generator.generate_and_register_factors(template_count, ai_count)